### ISSUE TITLE
Feature request - popup shouldn't appear immediately

### ISSUE THREAD

**Issue by ro31337** [mrd0x/BITB#2]
In the real world popup window won't appear immediately. The border gets rendered first, and then elements appear like in 0.5-1 seconds. It would be nice to incorporate that ;)

**Comment by Doomsdaybear** [comment]
My guess as an amateur is to have the window delay each "layer" that renders. Idk how that would be executed, but it's worth a look.

**Comment by mrd0x** [comment]
I pushed the `Windows-DarkMode-Delay` template. You can further modify the fade in timing in `script.js` to make it appear more realistic.
